name: Build Application
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # تم تغيير هذا من 18 إلى 20
      - name: Install and Build
        run: |
          rm -rf node_modules package-lock.json
          npm install
          npm run build
